name: 07 - Using Expressions
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] Print start-up data"
              if: ${{ github.event.inputs.debug == 'true' }}
              run: |
                    echo "Triggered by ${{ github.event_name }}"
                    echo " Branch: ${{ github.ref }}"
                    echo "Commit SHA: ${{ github.sha }}"
                    echo "Runner OS: ${{ runner.os }}"
            - name: "[debug] Print when triggered from main"
              if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.debug == 'true' }}
              run: echo "Running whenever a push is made to main"
            - name: Greeting
              run: echo "Hello, World!"
